HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 146
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: text/plain; charset=utf-8
ETag: "c3e5bc84f364bad35e6d603e44238ca11bc90520109fdb2d4f091222594fdc2c"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 132A:2FD98B:1397620:15B87BA:66948C9D
Accept-Ranges: bytes
Date: Mon, 15 Jul 2024 04:18:47 GMT
Via: 1.1 varnish
X-Served-By: cache-iad-kiad7000022-IAD
X-Cache: HIT
X-Cache-Hits: 0
X-Timer: S1721017128.652192,VS0,VE1
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 494ec7759ee2ab701b2a8de7c9bf3ced9edcab55
Expires: Mon, 15 Jul 2024 04:23:47 GMT
Source-Age: 209

HTTP/1.1 200 OK
Content-Type: text/plain
Transfer-Encoding: chunked

25  
This is the data in the first chunk

1C
and this is the second one

0  
