HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 202
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: text/plain; charset=utf-8
ETag: "216ffaedbfd62dc6335434069d74db9b07632cef474dcbe41f40fbb260c66afd"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: BDF6:25DE3F:132641F:1531A28:66949341
Accept-Ranges: bytes
Date: Mon, 15 Jul 2024 04:18:49 GMT
Via: 1.1 varnish
X-Served-By: cache-iad-kiad7000086-IAD
X-Cache: HIT
X-Cache-Hits: 0
X-Timer: S1721017130.618218,VS0,VE1
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: e049c19bc692c0d4e996e16513b0fd01dd9f1fd2
Expires: Mon, 15 Jul 2024 04:23:49 GMT
Source-Age: 207

v=0
o=root 2890844526 2890842807 IN IP4 10.4.247.130
s=DASH
t=0 32511974400
a=source-filter: incl IN IP4 * 10.4.247.130
a=flute-tsi:5
a=flute-ch:1
m=application 4005 FLUTE/UDP 0
c=IN IP4 224.1.1.1/4005
