HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 253
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: text/plain; charset=utf-8
ETag: "4725df3994d3c3ade2227596fd99b1eca0acfb9e94a9374d5b52856d1b0ee86b"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 0E9E:2BD128:13E199F:15ECFD3:66949345
Accept-Ranges: bytes
Date: Mon, 15 Jul 2024 04:18:50 GMT
Via: 1.1 varnish
X-Served-By: cache-iad-kiad7000127-IAD
X-Cache: HIT
X-Cache-Hits: 0
X-Timer: S1721017131.702900,VS0,VE1
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 3ad25c7b1a7ddb6c051225ce2958c18acc7bb7e1
Expires: Mon, 15 Jul 2024 04:23:50 GMT
Source-Age: 205

v=0
o=user 2890844526 2890842807 IN IP4 10.20.30.40
s=File delivery session example
i=More information
t=2873397496 2873404696
a=source-filter: incl IN IP4 * 10.20.30.40
a=flute-tsi:1
a=flute-ch:1
m=application 4001 FLUTE/UDP 0
c=IN IP4 226.10.40.1/15

